-- =====================================================
-- ⚠️ IMPORTANT: USE THE SAFE VERSION INSTEAD
-- =====================================================
-- 
-- This file has been superseded by: OWEN_SAFE_DATABASE_SETUP.sql
-- 
-- The new file is 100% safe to run even if objects already exist.
-- It will NOT produce errors about existing types, tables, or policies.
--
-- Please use: OWEN_SAFE_DATABASE_SETUP.sql
-- Read instructions in: OWEN_COMPLETE_SETUP_INSTRUCTIONS.md
--
-- =====================================================
