// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlvchryhaioxcrywwgwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdmNocnloYWlveGNyeXd3Z3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MjYyNjMsImV4cCI6MjA1MTUwMjI2M30.8FXFr5vWPbQvMYwxUh3q3uZ0XtJIpTJPH_3dNE_YBY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});