// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlvchryhaioxcrywwgwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sdmNocnloYWlveGNyeXd3Z3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDI3MjUsImV4cCI6MjA3NDkxODcyNX0.Vf4vQFCpIpaNNVY6aCyZwbmy1kLptHm7Z1sCOjCpeiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});